version: "2"
linters:
  enable:
    - sloglint
  exclusions:
    rules:
      - linters:
          - errcheck
        text: "Error return value of `.*.Close` is not checked"
  settings:
    sloglint:
      key-naming-case: snake
